### ISSUE TITLE
PATCHing account errors with sex.

### ISSUE THREAD

**Issue by iHiD** [ThalamusAI/kaido-issues#1]
PATCH’ing `https://platform.kaido.hosting/v1/account` returns

```
{
   “errors”: {
       “sex”: [
           “is not included in the list”
       ]
   }
}
```
no matter if it’s there, can you have a look please?

**Comment by kntsoriano** [comment]
This was caused by bad data in the accounts table. We we're unable to completely migrate records which had `sex` set to `0` or `1`.
